### ISSUE TITLE
Proposal: standalone coding dojo sessions for July and August enlieu of standard meetup event format

### ISSUE THREAD

**Issue by booyaa** [RustaceansUK/wiki#1]
Hi Christian,

Would you be interested in organising such an event? These events would replace the existing meetup (I don't think we're going to get many speakers for these summer months because of school breaks).

We could use July as the setup and hello world session start at 7pm wrap up by 9pm.

August would be the running start where we'd work on a problem together.

Let me know what you think. Me and @vladimir-lu would love to help you make this happen!

**Comment by pflanze** [comment]
Hey, noticed this long-standing issue while cleaning up things.

I've added the dojo idea to the home page of the wiki/website. But true, the dojo works well in a class room and could leave the hack evenings for actual active hacking. But then I wouldn't want to do any right now, need at least a little bit of competence first, also it may be more useful after the newbies amongst us have gone through the learning-from-the-book part, so that we all have at least a base level of understanding. Maybe we'll be ready for it these summer months?

**Comment by booyaa** [comment]
time has passed for this issue
